CREATE TABLE departments (id SERIAL PRIMARY KEY, name VARCHAR(50) NOT NULL, location VARCHAR(50));

CREATE TABLE employees (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	POSITION VARCHAR(50),
	salary NUMERIC(10, 2),
	department_id INTEGER REFERENCES departments (id) ON DELETE SET NULL,
	manager_id INTEGER REFERENCES employees (id) ON DELETE SET NULL
);

CREATE TABLE customers (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, city VARCHAR(50));

CREATE TABLE orders (
	id SERIAL PRIMARY KEY,
	order_date DATE NOT NULL,
	amount NUMERIC(10, 2),
	employee_id INTEGER REFERENCES employees (id) ON DELETE SET NULL,
	customer_id INTEGER REFERENCES customers (id) ON DELETE SET NULL
);

CREATE TABLE products (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, price NUMERIC(10, 2));

CREATE TABLE order_items (id SERIAL PRIMARY KEY, order_id INTEGER REFERENCES orders (id) ON DELETE CASCADE, product_id INTEGER REFERENCES products (id) ON DELETE SET NULL, quantity INTEGER NOT NULL);
